name: Git Diff Check
description: |
  Test if git diff contains any of the listed diff.
  This action will test if any of the files from the git diff contains one of the listed test strings.
inputs:
  before:
    description: Referenced commit hash
    required: true
  current:
    description: Commit hash to compare against before
    required: true
  tests:
    description: List of files/folders to test
    required: true
  assume_changes:
    description: Wether or not the script should assume changes on comparison error
    required: false
    default: "true"
outputs:
  contains_changes:
    description: Indicates that any of the tested files have changed or not
runs:
  using: node16
  main: dist/main.js
