name: Build and Push to ECR
description: |
  Build and push a docker image to ECR using cache from previous latest build.
  It will skip pushing new tag version if the current build is equal to the :latest build on ECR.
inputs:
  ecr_registry:
    description: ECR repository URI
    required: true
  image:
    description: Name of the image
    required: true
  tag:
    description: Image version tag
    required: true
  args:
    description: Additional arguments to pass to docker build
    required: false
  file:
    description: Dockerfile file location. Defaults to `${path}/Dockerfile`
    required: false
  path:
    description: Path to the context to build. Defaults to current working directory
    required: false
    default: "."
outputs:
  image_uri:
    description: ECR full URI of the generated image with the selected `tag`. Cannot be consumed by job outputs.
  image:
    description: Name of the generated image with the selected `tag`
  tag:
    description: The selected tag from the build. It can be either the input `tag` to this action of the tag of an image on ECR with the same digest.
runs:
  using: node12
  main: main.js
