name: Setup the SSH agent
description: This action allows to fetch private repositories
inputs:
  ssh-key:
    description: The private SSH key to use
    required: true
runs:
  using: node16
  main: dist/main.js
  post: dist/cleanup.js
