name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - handle-exit-codes

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./git-diff-check
        with:
          before: "9e270b2e71bb6e91df4a434270e8e4bd3cd4b85b"
          current: ${{ github.sha }}
          tests: |
            e
            dist
        id: diffs

      - run: echo "Contains changes = ${{ steps.diffs.outputs.contains_changes }}"
      # - run: yarn
      # - run: yarn lint
      # - run: yarn build-all
