name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use SSH
        uses: ./use-ssh
        with:
          ssh-key: "secrets.SSH_KEY"
      # - run: yarn
      # - run: yarn lint
      # - run: yarn build-all
