name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: yarn

      - run: yarn lint

      - run: yarn build-all

      - name: Test for missing dist compilations
        run: |
          distStatus=$(git status --porcelain "**/dist/*.js")
          if [ -z "$distStatus" ]; then 
            echo "✅ All action's dist folders are compiled."
          else
            echo "🚫 Some actions were not compiled."
            echo "Please run \`yarn build-all\` and commit."
            echo
            echo "Dist diff status:"
            echo "$distStatus"
            exit 1
          fi
